entryPoints:
  web:
    address: ":80"
  internal:
    address: ":9000"

providers:
  # Enable the file provider to define routers / middlewares / services in file
  file:
    directory: /etc/traefik
    watch: true

api:
  dashboard: true
  debug: true
